#!/usr/bin/python
# -*- coding: utf-8 -*-
# vim: set fileencoding=utf-8
# Copyright (c) 2008, 2010 Janne Blomqvist

#  This file is part of Vasputil; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public
#  License as published by the Free Software Foundation; either
#  version 2.1 of the License, or (at your option) any later version.
#  See the file COPYING for details.

"""Convert a POSCAR file from direct to cartesian coordinates."""

import ase.io
from optparse import OptionParser
import os.path

usage = """%prog [options] POSCAR"""

parser = OptionParser(usage)
parser.add_option("-o", "--output", dest="outfile", \
        help="Name of output file. Defaults to name of input file plus \
.cart extension")
(options, args) = parser.parse_args()
if options.outfile:
    fname = options.outfile
else:
    fname = os.path.basename(args[0]) + ".cart"
a = ase.io.read(args[0], format="vasp")
ase.io.write(fname, a, format="vasp", direct=False, sort=False)

