#!/usr/bin/python
# -*- coding: utf-8 -*-
# vim: set fileencoding=utf-8
# Copyright (c) 2008, 2010, 2012 Janne Blomqvist
# Copyright (c) 2011 Noam Bernstein, NRL

#  This file is part of Vasputil; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public
#  License as published by the Free Software Foundation; either
#  version 2.1 of the License, or (at your option) any later version.
#  See the file COPYING for details.

"""Compare to POSCAR files and print out atoms that have moved."""

import vasputil.supercell as s
import ase.io
from optparse import OptionParser

usage = """%prog [options] POSCAR1 POSCAR2"""

parser = OptionParser(usage)
parser.add_option("-t", "--tolerance", dest="tol", \
        help=u"Tolerance, default 0.1 Angstrom")
parser.add_option("-v", "--verbose", dest="verb", action="store_true", \
        help="Print out the distance moved and the relative vector as well.")
(options, args) = parser.parse_args()
if options.tol:
    tol = float(options.tol)
else:
    tol = 0.1
c1 = ase.io.read(args[0], format="vasp")
c2 = ase.io.read(args[1], format="vasp")

if options.verb:
    print 'Atom   Moved (Å)      dx (Å)      dy (Å)      dz (Å)'
    print '===================================================='
for at in s.atoms_moved(c1, c2, tol):
    if options.verb:
	if options.verb:
            print ("%4i %11.4f %11.4f %11.4f %11.4f" % (at[0], at[1], at[2][0], 
                                                        at[2][1], at[2][2]))
    else:
        print at[0],
