#!/usr/bin/python
# -*- coding: utf-8 -*-
# vim: set fileencoding=utf-8
# Copyright (c) 2008, 2010, 2011, 2016 Janne Blomqvist

# This source code file is subject to the terms of the LGPL 2.1
# License. See the file LICENSE for details.

"""Check nearest neighbors in a POSCAR file."""
from __future__ import print_function

import vasputil.supercell as s
import ase.io
from optparse import OptionParser

usage = """%prog [options] POSCAR"""

parser = OptionParser(usage)
parser.add_option("-t", "--tolerance", dest="tol", \
        help="Tolerance, default 1.0 Angstrom")
parser.add_option("-n", "--numneigh", dest="nn", \
        help="Number of nearest neighbors to print.")
(options, args) = parser.parse_args()
if options.tol:
    tol = float(options.tol)
else:
    tol = 1.0
c = ase.io.read(args[0], format='vasp')
if options.nn:
    nnd = s.nearest_neighbors(c, num_neigh=int(options.nn))
else:
    nnd = s.nearest_neighbors(c, tol=tol)
print('Atom  Atom    Dist (Å)')
print('======================')
for at in nnd:
    print("%4i  %4i  %10.2f" % at)
