#!/usr/bin/python
# -*- coding: latin-1 -*-

# Copyright (c) 2008 Janne Blomqvist

#  This file is part of Vasputil.

#  Vasputil is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.

#  Vasputil is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

#  You should have received a copy of the GNU General Public License
#  along with vasputil.  If not, see <http://www.gnu.org/licenses/>.

"""Simple arithmetic operations (+,-,*,/) on CHG/CHGCAR files"""

from optparse import OptionParser
from pylab import *
from ase.calculators.vasp import VaspChargeDensity

usage = """%prog [options] chgfile1 op chgfile2

chgfile1 and chgfile2 are the charge density files in VASP CHG or
CHGCAR format.  If the charge density files are not compatible, you
get what you deserve.

op is an elementary arithmetic operator (+,-,*,/), or avg to calculate
the average."""

parser = OptionParser(usage)
parser.add_option('-o', '--output', dest='outfile', help='Output to file \
named by this argument. If omitted, defaults to a file chgfile1_op_chgfile2')
(options, args) = parser.parse_args()

chgf1 = args[0]
chgf2 = args[2]
op = args[1]

chg1 = VaspChargeDensity(chgf1)
chg2 = VaspChargeDensity(chgf2)

if len(chg1.chg) != len(chg2.chg):
    print 'Number of images in charge density files not equal. Using just \
the final images in both files.'
    chg1.chg = [chg1.chg[-1]]
    chg1.atoms = [chg1.atoms[-1]]
    if chg1.is_spin_polarized():
        chg1.chgdiff = [chg1.chgdiff[-1]]
        chg2.chgdiff = [chg2.chgdiff[-1]]
    chg2.chg = [chg2.chg[-1]]
    chg2.atoms = [chg2.atoms[-1]]

newchg = VaspChargeDensity(None)
for i, atchg in enumerate(chg1.chg):
    c1 = atchg
    c2 = chg2.chg[i]
    newchg.atoms.append(chg1.atoms[i].copy())
    if op == '+':
        nc = c1 + c2
        oplong = '_add_'
    elif op == '-':
        nc = c1 - c2
        oplong = '_sub_'
    elif op == '*':
        nc = c1 * c2
        oplong = '_mult_'
    elif op == '/':
        nc = c1 / c2
        oplong = '_div_'
    elif op == 'avg':
        nc = (c1 + c2) / 2
        oplong = '_avg_'
    newchg.chg.append(nc)

if chg1.is_spin_polarized():
    for i, cd in enumerate(chg1.chgdiff):
        cd2 = chg2.chgdiff[i]
        if op == '+':
            nd = cd + cd2
        elif op == '-':
            nd = cd - cd2
        elif op == '*':
            nd = cd * cd2
        elif op == '/':
            nd = cd / cd2
        elif op == 'avg':
            nd = (cd + cd2) / 2
        newchg.chgdiff.append(nd)

# Screw doing anything fancy with the augmentation charges
newchg.aug = chg1.aug
newchg.augdiff = chg1.augdiff

if options.outfile:
    fname = options.outfile
else:
    from os.path import basename
    fname = basename(chgf1) + oplong + basename(chgf2)

newchg.write(fname)
