#!/usr/bin/python
# -*- coding: utf-8 -*-
# vim: set fileencoding=utf-8
# Copyright (c) 2008, 2010 Janne Blomqvist

# This source code file is subject to the terms of the MIT (Expat)
# License. See the file LICENSE for details.

"""Measure the distance between an atom and a plane."""

import ase.io
import vasputil.geometry as vg
from optparse import OptionParser
import time
import os.path

usage = """%prog [options] POSCAR p0 p1 p2 atom

atom is the index of the atom to measure the distance to. The plane is
defined by the atoms with indices p0-p2. Indices start from 0."""

parser = OptionParser(usage)
(options, args) = parser.parse_args()

poscar = ase.io.read(args[0], format='vasp')
ac = poscar.positions[int(args[4])]
p = [int(args[1]), int(args[2]), int(args[3])]
pc = poscar.positions[p]
plane = vg.Plane(pc)

print plane.distance(ac)
