#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: set fileencoding=utf-8
# Copyright (c) 2008, 2010, 2016 Janne Blomqvist

# This source code file is subject to the terms of the LGPL 2.1
# License. See the file LICENSE for details.

"""Convert a POSCAR file from direct to cartesian coordinates."""

import ase.io
from optparse import OptionParser
import os.path

usage = """%prog [options] POSCAR"""

parser = OptionParser(usage)
parser.add_option("-o", "--output", dest="outfile", \
        help="Name of output file. Defaults to name of input file plus \
.cart extension")
(options, args) = parser.parse_args()
if options.outfile:
    fname = options.outfile
else:
    fname = os.path.basename(args[0]) + ".cart"
a = ase.io.read(args[0], format="vasp")
ase.io.write(fname, a, format="vasp", direct=False, sort=False)

